In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
data=sns.load_dataset("tips")

In [5]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
data.to_csv("local_file.csv",index=False)

In [4]:
chart=pd.read_excel("Ecommerce Final.xlsx")

In [5]:
chart

Product ID Category Sub-category Product Name Brand Name   Size  \
0         P0001    Women      Topwear     T-Shirts   Roadster     40   
1         P0002    Women      Topwear     T-Shirts   Roadster     40   
2         P0003    Women      Topwear     T-Shirts   Roadster     42   
3         P0004    Women      Topwear     T-Shirts   Roadster     44   
4         P0005    Women      Topwear     T-Shirts       Puma     38   
...         ...      ...          ...          ...        ...    ...   
3066      P3067     Kids     Footwear      Sandals     Campus  9-12M   
3067      P3068     Kids     Footwear      Sandals     Campus  9-12M   
3068      P3069     Kids     Footwear      Sandals     Campus   3-6M   
3069      P3070     Kids     Footwear      Sandals     Campus   3-6M   
3070      P3071     Kids     Footwear      Sandals     Campus   3-6M   

               Color  Ratings  
0              Black        4  
1               Blue        5  
2              White        3  
3              Green        2  
4              Olive        5  
...              ...      ...  
3066           Olive        5  
3067            Teal        3  
3068       Sea Green        5  
3069  Turquoise Blue        5  
3070        Charcoal        4  

[3071 rows x 8 columns]

In [7]:
chart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3071 entries, 0 to 3070
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Product ID    3071 non-null   object
 1   Category      3071 non-null   object
 2   Sub-category  3071 non-null   object
 3   Product Name  3071 non-null   object
 4   Brand Name    3071 non-null   object
 5   Size          3071 non-null   object
 6   Color         3071 non-null   object
 7   Ratings       3071 non-null   int64 
dtypes: int64(1), object(7)
memory usage: 192.1+ KB


In [9]:
chart.describe()

Ratings
count  3071.000000
mean      4.002931
std       0.971411
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max       5.000000

In [10]:
chart.describe(include='all')

Product ID Category Sub-category Product Name Brand Name     Size  \
count        3071     3071         3071         3071       3071     3071   
unique       3071        4           11           40         72       41   
top         P3071    Women     Footwear        Jeans        H&M  Onesize   
freq            1      993          550          310        266      620   
mean          NaN      NaN          NaN          NaN        NaN      NaN   
std           NaN      NaN          NaN          NaN        NaN      NaN   
min           NaN      NaN          NaN          NaN        NaN      NaN   
25%           NaN      NaN          NaN          NaN        NaN      NaN   
50%           NaN      NaN          NaN          NaN        NaN      NaN   
75%           NaN      NaN          NaN          NaN        NaN      NaN   
max           NaN      NaN          NaN          NaN        NaN      NaN   

       Color      Ratings  
count   3071  3071.000000  
unique    42          NaN  
top     Pink          NaN  
freq     226          NaN  
mean     NaN     4.002931  
std      NaN     0.971411  
min      NaN     2.000000  
25%      NaN     3.000000  
50%      NaN     4.000000  
75%      NaN     5.000000  
max      NaN     5.000000

In [11]:
chart.columns

Index(['Product ID', 'Category', 'Sub-category', 'Product Name', 'Brand Name',
       'Size', 'Color', 'Ratings'],
      dtype='object')

In [13]:
chart['Category']

0       Women
1       Women
2       Women
3       Women
4       Women
        ...  
3066     Kids
3067     Kids
3068     Kids
3069     Kids
3070     Kids
Name: Category, Length: 3071, dtype: object

In [14]:
chart['Category'].unique()

array(['Women', 'Men', 'Beauty', 'Kids'], dtype=object)

In [15]:
chart['Category'].value_counts()

Category
Women     993
Men       989
Beauty    620
Kids      469
Name: count, dtype: int64

In [16]:
chart.head()

Product ID Category Sub-category Product Name Brand Name Size  Color  \
0      P0001    Women      Topwear     T-Shirts   Roadster   40  Black   
1      P0002    Women      Topwear     T-Shirts   Roadster   40   Blue   
2      P0003    Women      Topwear     T-Shirts   Roadster   42  White   
3      P0004    Women      Topwear     T-Shirts   Roadster   44  Green   
4      P0005    Women      Topwear     T-Shirts       Puma   38  Olive   

   Ratings  
0        4  
1        5  
2        3  
3        2  
4        5

In [18]:
chart.head(16)

Product ID Category Sub-category Product Name Brand Name Size      Color  \
0       P0001    Women      Topwear     T-Shirts   Roadster   40      Black   
1       P0002    Women      Topwear     T-Shirts   Roadster   40       Blue   
2       P0003    Women      Topwear     T-Shirts   Roadster   42      White   
3       P0004    Women      Topwear     T-Shirts   Roadster   44      Green   
4       P0005    Women      Topwear     T-Shirts       Puma   38      Olive   
5       P0006    Women      Topwear     T-Shirts       Puma   46       Pink   
6       P0007    Women      Topwear     T-Shirts       Puma   38     Orange   
7       P0008    Women      Topwear     T-Shirts       Puma   38      Beige   
8       P0009    Women      Topwear     T-Shirts       Puma   38  Off white   
9       P0010    Women      Topwear     T-Shirts       Puma   38     Purple   
10      P0011    Women      Topwear     T-Shirts       Puma   38      Peach   
11      P0012    Women      Topwear     T-Shirts       Puma   42  Sea Green   
12      P0013    Women      Topwear     T-Shirts       Puma   42   Lavender   
13      P0014    Women      Topwear     T-Shirts       Puma   42      Black   
14      P0015    Women      Topwear     T-Shirts       Puma   42       Blue   
15      P0016    Women      Topwear     T-Shirts       Puma   36      White   

    Ratings  
0         4  
1         5  
2         3  
3         2  
4         5  
5         4  
6         3  
7         5  
8         4  
9         2  
10        5  
11        5  
12        4  
13        4  
14        4  
15        3

In [19]:
chart.tail()

Product ID Category Sub-category Product Name Brand Name   Size  \
3066      P3067     Kids     Footwear      Sandals     Campus  9-12M   
3067      P3068     Kids     Footwear      Sandals     Campus  9-12M   
3068      P3069     Kids     Footwear      Sandals     Campus   3-6M   
3069      P3070     Kids     Footwear      Sandals     Campus   3-6M   
3070      P3071     Kids     Footwear      Sandals     Campus   3-6M   

               Color  Ratings  
3066           Olive        5  
3067            Teal        3  
3068       Sea Green        5  
3069  Turquoise Blue        5  
3070        Charcoal        4

In [20]:
chart.set_index('Size')

Product ID Category Sub-category Product Name Brand Name  \
Size                                                             
40         P0001    Women      Topwear     T-Shirts   Roadster   
40         P0002    Women      Topwear     T-Shirts   Roadster   
42         P0003    Women      Topwear     T-Shirts   Roadster   
44         P0004    Women      Topwear     T-Shirts   Roadster   
38         P0005    Women      Topwear     T-Shirts       Puma   
...          ...      ...          ...          ...        ...   
9-12M      P3067     Kids     Footwear      Sandals     Campus   
9-12M      P3068     Kids     Footwear      Sandals     Campus   
3-6M       P3069     Kids     Footwear      Sandals     Campus   
3-6M       P3070     Kids     Footwear      Sandals     Campus   
3-6M       P3071     Kids     Footwear      Sandals     Campus   

                Color  Ratings  
Size                            
40              Black        4  
40               Blue        5  
42              White        3  
44              Green        2  
38              Olive        5  
...               ...      ...  
9-12M           Olive        5  
9-12M            Teal        3  
3-6M        Sea Green        5  
3-6M   Turquoise Blue        5  
3-6M         Charcoal        4  

[3071 rows x 7 columns]

In [21]:
iu=sns.load_dataset('titanic')

In [22]:
iu

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [23]:
iu.to_csv("Loaded_data.csv",index=False)

In [24]:
iu.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [25]:
iu[['survived','sex','age','fare']]

survived     sex   age     fare
0           0    male  22.0   7.2500
1           1  female  38.0  71.2833
2           1  female  26.0   7.9250
3           1  female  35.0  53.1000
4           0    male  35.0   8.0500
..        ...     ...   ...      ...
886         0    male  27.0  13.0000
887         1  female  19.0  30.0000
888         0  female   NaN  23.4500
889         1    male  26.0  30.0000
890         0    male  32.0   7.7500

[891 rows x 4 columns]

In [26]:
type(iu)

pandas.core.frame.DataFrame

In [27]:
type(iu[['survived','sex','age','fare']])

pandas.core.frame.DataFrame

In [28]:
type(iu['survived'])

pandas.core.series.Series

In [29]:
iu.isnull()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False       False   True        False  False  False  
1    False       False  False        False  False  False  
2    False       False   True        False  False  False  
3    False       False  False        False  False  False  
4    False       False   True        False  False  False  
..     ...         ...    ...          ...    ...    ...  
886  False       False   True        False  False  False  
887  False       False  False        False  False  False  
888  False       False   True        False  False  False  
889  False       False  False        False  False  False  
890  False       False   True        False  False  False  

[891 rows x 15 columns]

In [30]:
iu.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [31]:
iu.isnull().sum().sum()

np.int64(869)

In [32]:
import numpy as np

In [33]:
l=[1,2,3,4]
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [34]:
s="LPU IBM Kabir UNIversity "
arr2=np.array(s)
arr2

array('LPU IBM Kabir UNIversity ', dtype='<U25')

In [35]:
arr3=np.array(["S",567,True,"kjhgf"])
arr3

array(['S', '567', 'True', 'kjhgf'], dtype='<U21')

In [36]:
arr4=np.arange(10,dtype="float") # syn 1
arr4

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
arr5=np.arange(10,20) # syn 2
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
arr6=np.arange(10,20,2) # syn 3
arr6

array([10, 12, 14, 16, 18])

In [39]:
arr7=np.zeros(7)
arr7

array([0., 0., 0., 0., 0., 0., 0.])

In [40]:
arr8=np.zeros((7,8))
arr8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
arr9=np.ones(3)
arr9

array([1., 1., 1.])

In [42]:
arr10=np.ones((3,3))
arr10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])